version: 2

updates:
  - package-ecosystem: pip
    directory: /backend
    schedule:
      interval: monthly
      time: "06:00"
      timezone: America/Bahia
    open-pull-requests-limit: 1
    groups:
      backend-minor-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major

  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: monthly
      time: "06:10"
      timezone: America/Bahia
    open-pull-requests-limit: 1
    groups:
      frontend-minor-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major

  - package-ecosystem: docker
    directory: /backend
    schedule:
      interval: monthly
      time: "06:20"
      timezone: America/Bahia
    open-pull-requests-limit: 1
    groups:
      backend-container-minor-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major

  - package-ecosystem: docker
    directory: /frontend
    schedule:
      interval: monthly
      time: "06:30"
      timezone: America/Bahia
    open-pull-requests-limit: 1
    groups:
      frontend-container-minor-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
      time: "06:40"
      timezone: America/Bahia
    open-pull-requests-limit: 1
    groups:
      actions-minor-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
