services:
  migrate:
    image: ${API_IMAGE:-ghcr.io/wkarts/argws-git-monitor-api}:latest
    pull_policy: always
  api:
    image: ${API_IMAGE:-ghcr.io/wkarts/argws-git-monitor-api}:latest
    pull_policy: always
  worker:
    image: ${API_IMAGE:-ghcr.io/wkarts/argws-git-monitor-api}:latest
    pull_policy: always
  beat:
    image: ${API_IMAGE:-ghcr.io/wkarts/argws-git-monitor-api}:latest
    pull_policy: always
  web:
    image: ${WEB_IMAGE:-ghcr.io/wkarts/argws-git-monitor-web}:latest
    pull_policy: always
