<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { Activity, Braces, Check, Copy, ExternalLink, KeyRound, RefreshCw, ShieldCheck, Terminal, Trash2, Webhook } from 'lucide-vue-next'
import { ApiError, api } from '../services/api'
import { useDialogStore } from '../stores/dialog'
import { useToastStore } from '../stores/toast'

interface ApiScope { scope:string; description:string }
interface ApiKeyItem { id:string; name:string; prefix:string; scopes:string[]; enabled:boolean; expires_at:string|null; last_used_at:string|null; created_at:string; token?:string; warning?:string }

const dialogs=useDialogStore()
const toasts=useToastStore()
const loading=ref(true)
const busy=ref('')
const scopes=ref<ApiScope[]>([])
const keys=ref<ApiKeyItem[]>([])
const createdToken=ref('')
const copied=ref(false)
const formOpen=ref(false)
const form=reactive({name:'Integração Git Monitor',scopes:['monitoring:read','repositories:read'] as string[],expires_at:''})

const externalBase=computed(()=>`${window.location.origin}/api/v1/external/v1`)
const docsUrl=computed(()=>`${window.location.origin}/api/v1/docs`)
const enabledKeys=computed(()=>keys.value.filter(item=>item.enabled))
const usedKeys=computed(()=>keys.value.filter(item=>item.last_used_at))
const uniqueScopes=computed(()=>new Set(keys.value.flatMap(item=>item.scopes)).size)
const curlExample=computed(()=>`curl -H "X-API-Key: agm_SEU_TOKEN" \\\n  "${externalBase.value}/status"`)
const repoExample=computed(()=>`curl -H "Authorization: Bearer agm_SEU_TOKEN" \\\n  "${externalBase.value}/repositories"`)

function errorMessage(error:unknown):string{return error instanceof ApiError?error.message:String(error)}
function when(value:string|null):string{return value?new Date(value).toLocaleString('pt-BR'):'Nunca'}
function relativeExpiry(value:string|null):string{if(!value)return'Sem expiração';const diff=new Date(value).getTime()-Date.now();if(diff<=0)return'Expirada';const days=Math.ceil(diff/86400000);return days===1?'Expira amanhã':`Expira em ${days} dias`}
async function load():Promise<void>{loading.value=true;try{const [scopeData,keyData]=await Promise.all([api.get<ApiScope[]>('/api-access/scopes'),api.get<ApiKeyItem[]>('/api-access/keys')]);scopes.value=scopeData;keys.value=keyData}catch(error){toasts.error('Falha ao carregar API & Integrações',errorMessage(error))}finally{loading.value=false}}
function toggleScope(scope:string):void{const index=form.scopes.indexOf(scope);if(index>=0)form.scopes.splice(index,1);else form.scopes.push(scope)}
async function createKey():Promise<void>{if(!form.name.trim()||!form.scopes.length)return;busy.value='create';try{const created=await api.post<ApiKeyItem>('/api-access/keys',{name:form.name.trim(),scopes:[...form.scopes],expires_at:form.expires_at?new Date(form.expires_at).toISOString():null});createdToken.value=created.token||'';copied.value=false;formOpen.value=false;toasts.success('Chave criada','Copie o segredo agora; ele não será exibido novamente.');await load()}catch(error){toasts.error('Não foi possível criar a chave',errorMessage(error))}finally{busy.value=''}}
async function copyText(value:string,label='Conteúdo'):Promise<void>{try{await navigator.clipboard.writeText(value);toasts.success(`${label} copiado`)}catch{toasts.error('Não foi possível copiar automaticamente')}}
async function copyToken():Promise<void>{if(!createdToken.value)return;await copyText(createdToken.value,'Chave');copied.value=true}
async function revoke(key:ApiKeyItem):Promise<void>{const accepted=await dialogs.askConfirmation({title:'Revogar chave de integração?',message:`${key.name} perderá acesso imediatamente. Sistemas que ainda usam agm_${key.prefix}_… passarão a receber acesso negado.`,tone:'danger',confirmLabel:'Revogar chave'});if(!accepted)return;busy.value=key.id;try{await api.delete(`/api-access/keys/${key.id}`);toasts.success('Chave revogada');await load()}catch(error){toasts.error('Falha ao revogar',errorMessage(error))}finally{busy.value=''}}
onMounted(load)
</script>

<template>
  <div class="page-stack api-page">
    <section class="hero-panel api-hero"><div><span class="eyebrow">API & INTEGRAÇÕES</span><h2>Integrações externas com controle real</h2><p>Crie credenciais independentes do login e do token GitHub, limite cada integração por escopo e acompanhe uso, expiração e revogação em uma interface única.</p><div class="button-row hero-actions"><button class="button primary" @click="formOpen=!formOpen"><KeyRound :size="16"/>Nova chave</button><a class="button secondary" :href="docsUrl" target="_blank" rel="noreferrer"><ExternalLink :size="16"/>OpenAPI</a><button class="button ghost" :disabled="loading" @click="load"><RefreshCw :size="16"/>Atualizar</button></div></div><div class="metric-grid hero-metrics"><article class="metric-card"><span>Ativas</span><strong>{{enabledKeys.length}}</strong><small>{{keys.length}} cadastrada(s)</small></article><article class="metric-card"><span>Já utilizadas</span><strong>{{usedKeys.length}}</strong><small>com atividade registrada</small></article><article class="metric-card"><span>Escopos em uso</span><strong>{{uniqueScopes}}</strong><small>permissões distintas</small></article><article class="metric-card"><span>Endpoint</span><strong>v1</strong><small>API externa estável</small></article></div></section>
    <section class="panel endpoint-panel"><header><div><strong>Endpoint externo</strong><span>Use somente esta base nas aplicações integradas.</span></div><span class="status-pill ok"><Activity :size="12"/>Disponível</span></header><div class="endpoint-row"><code>{{externalBase}}</code><button class="button secondary compact" @click="copyText(externalBase,'Endpoint')"><Copy :size="14"/>Copiar</button></div></section>
    <section v-if="formOpen" class="panel"><header><div><strong>Nova credencial</strong><span>Conceda somente os escopos necessários.</span></div><ShieldCheck :size="20"/></header><div class="form-grid"><label class="field"><span>Nome da integração</span><input v-model="form.name" maxlength="160"/></label><label class="field"><span>Expiração opcional</span><input v-model="form.expires_at" type="datetime-local"/></label></div><div class="scope-grid"><button v-for="item in scopes" :key="item.scope" class="scope-card" :class="{active:form.scopes.includes(item.scope)}" @click="toggleScope(item.scope)"><span class="scope-check"><Check v-if="form.scopes.includes(item.scope)" :size="14"/></span><div><strong>{{item.scope}}</strong><small>{{item.description}}</small></div></button></div><div class="button-row"><button class="button primary" :disabled="busy==='create'||!form.name.trim()||!form.scopes.length" @click="createKey"><KeyRound :size="16"/>Gerar chave segura</button><button class="button ghost" @click="formOpen=false">Cancelar</button></div></section>
    <section v-if="createdToken" class="panel token-panel"><header><div><strong>Segredo exibido uma única vez</strong><span>Copie agora e armazene no cofre de segredos do sistema consumidor.</span></div></header><div class="token-box"><code>{{createdToken}}</code><button class="button primary compact" @click="copyToken"><Check v-if="copied" :size="14"/><Copy v-else :size="14"/>{{copied?'Copiada':'Copiar chave'}}</button></div></section>
    <div class="pro-grid"><section class="panel pro-span-6"><header><div><strong>Teste rápido</strong><span>Consulta de saúde com X-API-Key.</span></div><Terminal :size="18"/></header><pre class="code-block">{{curlExample}}</pre><button class="button ghost compact" @click="copyText(curlExample,'Exemplo')"><Copy :size="14"/>Copiar exemplo</button></section><section class="panel pro-span-6"><header><div><strong>Repositórios</strong><span>Exemplo usando Bearer sem expor token GitHub.</span></div><Braces :size="18"/></header><pre class="code-block">{{repoExample}}</pre><button class="button ghost compact" @click="copyText(repoExample,'Exemplo')"><Copy :size="14"/>Copiar exemplo</button></section></div>
    <section class="panel"><header><div><strong>Como integrar</strong><span>Fluxo recomendado para sistemas externos.</span></div><Webhook :size="20"/></header><div class="guide-grid"><article><b>1</b><div><strong>Crie uma chave</strong><p>Nomeie e limite os escopos.</p></div></article><article><b>2</b><div><strong>Guarde o segredo</strong><p>O token completo aparece uma única vez.</p></div></article><article><b>3</b><div><strong>Consuma /external/v1</strong><p>Envie X-API-Key ou Bearer.</p></div></article><article><b>4</b><div><strong>Revogue quando quiser</strong><p>A revogação é imediata.</p></div></article></div></section>
    <section class="panel"><header><div><strong>Credenciais cadastradas</strong><span>{{enabledKeys.length}} ativa(s)</span></div></header><div v-if="!keys.length&&!loading" class="empty">Nenhuma chave externa criada.</div><div v-else class="key-grid"><article v-for="item in keys" :key="item.id" class="key-card"><div class="key-head"><div><strong>{{item.name}}</strong><code>agm_{{item.prefix}}_…</code></div><span class="status-pill" :class="item.enabled?'ok':'bad'">{{item.enabled?'Ativa':'Revogada'}}</span></div><div class="scope-list"><code v-for="scope in item.scopes" :key="scope">{{scope}}</code></div><div class="key-meta"><span>Último uso <strong>{{when(item.last_used_at)}}</strong></span><span>Expiração <strong>{{relativeExpiry(item.expires_at)}}</strong></span></div><button v-if="item.enabled" class="button ghost danger-text" :disabled="busy===item.id" @click="revoke(item)"><Trash2 :size="14"/>Revogar chave</button></article></div></section>
  </div>
</template>

<style scoped>
.api-hero{align-items:center}.hero-actions{margin-top:1rem}.endpoint-panel{display:grid;gap:.7rem}.endpoint-row,.token-box{display:flex;align-items:center;gap:.6rem;padding:.68rem;border:1px solid var(--border-soft);border-radius:.8rem;background:var(--surface-raised)}.endpoint-row code,.token-box code{flex:1;min-width:0;overflow-wrap:anywhere;color:var(--text-strong);font-size:.68rem}.form-grid{display:grid;grid-template-columns:2fr 1fr;gap:.7rem;margin-top:.7rem}.scope-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:.55rem;margin:.8rem 0}.scope-card{display:flex;gap:.55rem;padding:.7rem;text-align:left;border:1px solid var(--border);border-radius:.75rem;background:var(--surface-raised);cursor:pointer}.scope-card.active{border-color:var(--primary);background:color-mix(in srgb,var(--primary) 7%,var(--surface))}.scope-check{display:grid;place-items:center;flex:none;width:1.2rem;height:1.2rem;border:1px solid var(--border);border-radius:.35rem}.scope-card.active .scope-check{color:#fff;background:var(--primary)}.scope-card div{display:grid;gap:.15rem}.scope-card strong{color:var(--text-strong);font-size:.66rem}.scope-card small{color:var(--text-muted);font-size:.58rem}.token-panel{border-color:color-mix(in srgb,var(--success) 40%,var(--border))}.guide-grid,.key-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:.6rem}.guide-grid article{display:flex;gap:.55rem;padding:.65rem;border:1px solid var(--border-soft);border-radius:.75rem;background:var(--surface-raised)}.guide-grid b{display:grid;place-items:center;width:1.5rem;height:1.5rem;flex:none;color:#fff;border-radius:.5rem;background:var(--primary)}.guide-grid strong,.key-card strong{color:var(--text-strong);font-size:.67rem}.guide-grid p{margin:.15rem 0 0;color:var(--text-muted);font-size:.58rem;line-height:1.4}.key-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.key-card{display:grid;gap:.55rem;padding:.75rem;border:1px solid var(--border-soft);border-radius:.8rem;background:var(--surface-raised)}.key-head{display:flex;align-items:flex-start;justify-content:space-between;gap:.5rem}.key-head>div{display:grid;gap:.2rem}.key-head code{font-size:.57rem;color:var(--text-muted)}.scope-list{display:flex;flex-wrap:wrap;gap:.25rem}.scope-list code{padding:.18rem .32rem;border-radius:.35rem;background:var(--surface);font-size:.54rem}.key-meta{display:grid;grid-template-columns:1fr 1fr;gap:.5rem;color:var(--text-muted);font-size:.57rem}.key-meta span{display:grid}.key-meta strong{font-size:.6rem}.empty{padding:2rem;text-align:center;color:var(--text-muted)}.danger-text{color:var(--danger)!important}@media(max-width:900px){.scope-grid,.guide-grid{grid-template-columns:repeat(2,1fr)}.key-grid{grid-template-columns:1fr}}@media(max-width:620px){.form-grid,.scope-grid,.guide-grid{grid-template-columns:1fr}.endpoint-row,.token-box{align-items:stretch;flex-direction:column}.endpoint-row .button,.token-box .button{width:100%}}
</style>
