<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { Download, RefreshCw, Search, ShieldCheck } from 'lucide-vue-next'
import { ApiError, api } from '../services/api'
import { useToastStore } from '../stores/toast'

interface AuditRow { id:string; user_id:string|null; action:string; entity_type:string|null; entity_id:string|null; details:Record<string,unknown>; ip_address:string|null; created_at:string }
const toasts=useToastStore(); const rows=ref<AuditRow[]>([]); const loading=ref(true); const filter=ref(''); const busy=ref(false)
function err(error:unknown){return error instanceof ApiError?error.message:String(error)}
async function load(){loading.value=true;try{const query=filter.value.trim()?`?limit=500&operation_prefix=${encodeURIComponent(filter.value.trim())}`:'?limit=500';rows.value=await api.get<AuditRow[]>(`/platform/audit${query}`)}catch(error){toasts.error('Falha ao carregar auditoria',err(error))}finally{loading.value=false}}
async function download(){busy.value=true;try{const result=await api.download('/platform/audit.csv?limit=10000');const url=URL.createObjectURL(result.blob);const a=document.createElement('a');a.href=url;a.download=result.filename||'argws-git-monitor-audit.csv';a.click();URL.revokeObjectURL(url)}catch(error){toasts.error('Falha ao exportar',err(error))}finally{busy.value=false}}
function when(value:string){return new Date(value).toLocaleString('pt-BR')}
onMounted(load)
</script>
<template><div class="page-stack"><section class="page-heading"><div><span class="eyebrow">GOVERNANÇA</span><h2>Audit Log</h2><p>Trilha permanente das operações administrativas e destrutivas executadas pela plataforma.</p></div><div class="actions"><button class="button secondary" @click="load"><RefreshCw :size="16"/>Atualizar</button><button class="button primary" :disabled="busy" @click="download"><Download :size="16"/>CSV</button></div></section><section class="notice"><ShieldCheck :size="18"/><div><strong>Auditoria operacional</strong><span>Backup, restore, deploy, rollback, cleanup, releases, providers e operações administrativas registram usuário, entidade, parâmetros seguros, resultado e IP quando disponível.</span></div></section><section class="filter"><label class="field"><span>Prefixo da operação</span><div class="input-with-icon"><Search :size="15"/><input v-model="filter" placeholder="backup.  deployment.  cleanup." @keyup.enter="load"/></div></label><button class="button secondary" @click="load">Filtrar</button></section><section class="panel"><div class="table-wrap"><table><thead><tr><th>Data</th><th>Operação</th><th>Entidade</th><th>IP</th><th>Detalhes</th></tr></thead><tbody><tr v-for="row in rows" :key="row.id"><td>{{when(row.created_at)}}</td><td><code>{{row.action}}</code></td><td>{{row.entity_type||'—'}}<small>{{row.entity_id||''}}</small></td><td>{{row.ip_address||'—'}}</td><td><details><summary>Ver</summary><pre>{{JSON.stringify(row.details,null,2)}}</pre></details></td></tr><tr v-if="!rows.length&&!loading"><td colspan="5" class="empty">Nenhum registro para o filtro informado.</td></tr></tbody></table></div></section></div></template>
<style scoped>.actions{display:flex;gap:.5rem;flex-wrap:wrap}.notice{display:flex;gap:.7rem;padding:.8rem;border:1px solid color-mix(in srgb,var(--success) 28%,var(--border));border-radius:.85rem;background:color-mix(in srgb,var(--success) 5%,var(--surface))}.notice div{display:grid}.notice span{font-size:.67rem;color:var(--text-muted)}.filter{display:grid;grid-template-columns:1fr auto;gap:.6rem;align-items:end}.panel{border:1px solid var(--border);border-radius:.9rem;background:var(--surface);overflow:hidden}.table-wrap{overflow:auto}table{width:100%;border-collapse:collapse;font-size:.68rem}th,td{padding:.65rem;border-bottom:1px solid var(--border-soft);text-align:left;vertical-align:top}th{color:var(--text-muted)}td small{display:block;color:var(--text-muted);font-size:.56rem}pre{max-width:620px;max-height:250px;overflow:auto;padding:.6rem;border-radius:.55rem;background:var(--surface-raised);color:var(--text);font-size:.6rem}.empty{text-align:center;color:var(--text-muted)}@media(max-width:820px){.filter{grid-template-columns:1fr}.table-wrap{font-size:.62rem}}</style>
