<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { Activity, Boxes, Play, RefreshCw, RotateCcw, Server, ShieldCheck, Terminal } from 'lucide-vue-next'
import { ApiError, api } from '../services/api'
import { useDialogStore } from '../stores/dialog'
import { useToastStore } from '../stores/toast'
import type { PaginatedResponse, Repository } from '../types/api'

interface DeploymentTarget { id:string; repository_id:string|null; name:string; environment:string; strategy:string; host:string; port:number; username:string; working_directory:string; domain:string|null; healthcheck_url:string|null; config:Record<string,unknown>; enabled:boolean; created_at:string; updated_at:string }
interface DeploymentRecord { id:string; target_id:string; repository_id:string|null; job_id:string|null; status:string; requested_ref:string|null; previous_version:Record<string,unknown>; deployed_version:Record<string,unknown>; pipeline:Array<Record<string,unknown>>; health_result:Record<string,unknown>; error:string|null; started_at:string|null; completed_at:string|null; created_at:string }

const dialogs=useDialogStore(); const toasts=useToastStore(); const loading=ref(true); const busy=ref(''); const repositories=ref<Repository[]>([]); const targets=ref<DeploymentTarget[]>([]); const deployments=ref<DeploymentRecord[]>([])
const targetForm=reactive({repository_id:'',name:'Produção',environment:'production',strategy:'docker_compose',host:'',port:22,username:'deploy',working_directory:'/home/deploy/app',domain:'',healthcheck_url:'',configText:'{"compose_file":"compose.yaml"}',secretText:'{}'})
const deployForm=reactive({target_id:'',repository_id:'',ref:'main',release_url:'',checksum_sha256:'',confirmation:''})
const selectedTarget=computed(()=>targets.value.find(x=>x.id===deployForm.target_id)||null)
const repositoryMap=computed(()=>Object.fromEntries(repositories.value.map(x=>[x.id,x.full_name])))
const targetMap=computed(()=>Object.fromEntries(targets.value.map(x=>[x.id,`${x.environment} · ${x.name}`])))
function err(error:unknown){return error instanceof ApiError?error.message:String(error)}
function jsonObject(value:string){const parsed=JSON.parse(value||'{}') as unknown;if(!parsed||Array.isArray(parsed)||typeof parsed!=='object')throw new Error('Informe objeto JSON válido.');return parsed as Record<string,unknown>}
function when(value:string|null){return value?new Date(value).toLocaleString('pt-BR'):'—'}
function statusClass(status:string){return ['completed','rolled_back'].includes(status)?'ok':status.includes('warning')?'warn':status==='failed'?'bad':'run'}
async function loadRepos(){const items:Repository[]=[];let page=1,pages=1;do{const r=await api.get<PaginatedResponse<Repository>>(`/repositories?page=${page}&page_size=100`);items.push(...r.items);pages=r.pages;page++}while(page<=pages);return items}
async function load(){loading.value=true;try{const [repos,t,d]=await Promise.all([loadRepos(),api.get<DeploymentTarget[]>('/platform/deployment-targets'),api.get<DeploymentRecord[]>('/platform/deployments?limit=150')]);repositories.value=repos;targets.value=t;deployments.value=d;if(!targetForm.repository_id)targetForm.repository_id=repos[0]?.id||'';if(!deployForm.repository_id)deployForm.repository_id=repos[0]?.id||'';if(!deployForm.target_id)deployForm.target_id=t[0]?.id||''}catch(error){toasts.error('Falha ao carregar Deployments',err(error))}finally{loading.value=false}}
async function run(key:string,fn:()=>Promise<void>){busy.value=key;try{await fn()}catch(error){toasts.error('Operação recusada',err(error))}finally{busy.value=''}}
async function createTarget(){await run('create-target',async()=>{const created=await api.post<DeploymentTarget>('/platform/deployment-targets',{repository_id:targetForm.repository_id||null,name:targetForm.name,environment:targetForm.environment,strategy:targetForm.strategy,host:targetForm.host,port:targetForm.port,username:targetForm.username,working_directory:targetForm.working_directory,domain:targetForm.domain||null,healthcheck_url:targetForm.healthcheck_url||null,config:jsonObject(targetForm.configText),secret:jsonObject(targetForm.secretText),enabled:true});targetForm.secretText='{}';toasts.success('Deployment Target criado',`${created.name} · ${created.host}`);await load();deployForm.target_id=created.id})}
async function testTarget(target:DeploymentTarget){await run(`test-${target.id}`,async()=>{const result=await api.post<{ok:boolean;message:string;details:unknown}>(`/platform/deployment-targets/${target.id}/test`,{});result.ok?toasts.success('SSH validado',result.message):toasts.error('Target indisponível',result.message)})}
function prepareDeploy(target:DeploymentTarget){deployForm.target_id=target.id;if(target.repository_id)deployForm.repository_id=target.repository_id;const repo=repositories.value.find(r=>r.id===deployForm.repository_id);deployForm.ref=repo?.default_branch||'main';deployForm.confirmation=`DEPLOY ${target.name} ${deployForm.ref}`;document.getElementById('deploy-execute')?.scrollIntoView({behavior:'smooth'})}
async function deployNow(){
  if(!selectedTarget.value)return
  deployForm.confirmation=`DEPLOY ${selectedTarget.value.name} ${deployForm.ref}`
  const confirmed=await dialogs.askText({
    title:'Confirmar deployment remoto',
    message:`Ambiente: ${selectedTarget.value.environment}\nTarget: ${selectedTarget.value.name}\nRef: ${deployForm.ref}`,
    tone:'warning',
    confirmLabel:'Executar deploy',
    promptLabel:'Confirmação obrigatória',
    promptExpected:deployForm.confirmation,
    promptPlaceholder:deployForm.confirmation,
  })
  if(confirmed!==deployForm.confirmation)return
  await run('deploy',async()=>{const result=await api.post<{job_id:string}>(`/platform/deployment-targets/${selectedTarget.value!.id}/deploy`,{repository_id:deployForm.repository_id,ref:deployForm.ref,release_url:deployForm.release_url||null,checksum_sha256:deployForm.checksum_sha256||null,confirmation:confirmed});toasts.success('Deploy enfileirado',`Job ${result.job_id}. Pipeline e logs estão na Fila.`);await load()})
}
async function rollback(record:DeploymentRecord){
  const expected=`ROLLBACK ${record.id}`
  const confirmation=await dialogs.askText({
    title:'Confirmar rollback',
    message:'Rollback não é executado cegamente. Confirme o identificador da implantação antes de prosseguir.',
    tone:'danger',
    confirmLabel:'Executar rollback',
    promptLabel:'Confirmação obrigatória',
    promptExpected:expected,
    promptPlaceholder:expected,
  })
  if(confirmation!==expected)return
  await run(`rollback-${record.id}`,async()=>{const result=await api.post<{job_id:string}>(`/platform/deployments/${record.id}/rollback`,{confirmation});toasts.success('Rollback enfileirado',`Job ${result.job_id}`)})
}
onMounted(load)
</script>

<template><div class="page-stack">
  <section class="page-heading"><div><span class="eyebrow">DELIVERY E INFRAESTRUTURA</span><h2>Deployment Manager</h2><p>VPS, CloudPanel via SSH controlado, Docker Compose, releases, healthcheck e rollback auditável.</p></div><button class="button secondary" :disabled="loading" @click="load"><RefreshCw :size="16"/>Atualizar</button></section>
  <section class="notice"><ShieldCheck :size="18"/><div><strong>Sem endpoints inventados do CloudPanel</strong><span>Quando não existe API oficial suportada, o target usa SSH/agent e comandos explicitamente configurados. O Git Monitor não monta Docker Socket no container da API.</span></div></section>
  <section class="panel"><header><div><strong>Novo Deployment Target</strong><span>Cadastre desenvolvimento, homologação, staging, produção ou servidor personalizado.</span></div><Server :size="20"/></header><div class="grid cols-3"><label class="field"><span>Nome</span><input v-model="targetForm.name"/></label><label class="field"><span>Ambiente</span><input v-model="targetForm.environment" placeholder="production"/></label><label class="field"><span>Estratégia</span><select v-model="targetForm.strategy"><option value="git">Git Deployment</option><option value="release">Release Deployment</option><option value="docker_compose">Docker Compose</option></select></label></div><div class="grid cols-3"><label class="field"><span>Repositório</span><select v-model="targetForm.repository_id"><option value="">Sem vínculo fixo</option><option v-for="repo in repositories" :key="repo.id" :value="repo.id">{{repo.full_name}}</option></select></label><label class="field"><span>Host</span><input v-model="targetForm.host"/></label><label class="field"><span>Porta SSH</span><input v-model.number="targetForm.port" type="number" min="1" max="65535"/></label></div><div class="grid cols-2"><label class="field"><span>Usuário SSH</span><input v-model="targetForm.username"/></label><label class="field"><span>Diretório</span><input v-model="targetForm.working_directory"/></label></div><div class="grid cols-2"><label class="field"><span>Domínio</span><input v-model="targetForm.domain" placeholder="app.exemplo.com"/></label><label class="field"><span>Healthcheck URL</span><input v-model="targetForm.healthcheck_url" placeholder="https://app.exemplo.com/health"/></label></div><div class="grid cols-2"><label class="field"><span>Config JSON</span><textarea v-model="targetForm.configText" class="code"/></label><label class="field"><span>Credencial JSON</span><textarea v-model="targetForm.secretText" class="code" placeholder='{"private_key":"..."} ou {"password":"..."}'/></label></div><button class="button primary" :disabled="busy==='create-target'||!targetForm.host" @click="createTarget"><Server :size="15"/>Salvar target</button></section>
  <section class="cards"><article v-for="target in targets" :key="target.id" class="card"><header><div><strong>{{target.environment}} · {{target.name}}</strong><span>{{target.strategy}}</span></div><span class="dot" :class="{off:!target.enabled}"/></header><p><b>{{target.username}}@{{target.host}}:{{target.port}}</b><br><code>{{target.working_directory}}</code></p><small>{{target.repository_id?repositoryMap[target.repository_id]:'Target compartilhado'}} · {{target.healthcheck_url||'sem healthcheck'}}</small><div class="actions"><button class="button secondary" @click="testTarget(target)"><Activity :size="14"/>Testar</button><button class="button primary" @click="prepareDeploy(target)"><Play :size="14"/>Deploy</button></div></article></section>
  <section id="deploy-execute" class="panel"><header><div><strong>Executar Deployment</strong><span>A confirmação textual é calculada a partir do target e da referência.</span></div><Terminal :size="20"/></header><div class="grid cols-3"><label class="field"><span>Target</span><select v-model="deployForm.target_id"><option v-for="target in targets" :key="target.id" :value="target.id">{{target.environment}} · {{target.name}}</option></select></label><label class="field"><span>Repositório</span><select v-model="deployForm.repository_id"><option v-for="repo in repositories" :key="repo.id" :value="repo.id">{{repo.full_name}}</option></select></label><label class="field"><span>Ref/tag/commit</span><input v-model="deployForm.ref"/></label></div><div v-if="selectedTarget?.strategy==='release'" class="grid cols-2"><label class="field"><span>Release URL</span><input v-model="deployForm.release_url"/></label><label class="field"><span>SHA-256</span><input v-model="deployForm.checksum_sha256" maxlength="64"/></label></div><button class="button primary" :disabled="busy==='deploy'||!selectedTarget||!deployForm.repository_id" @click="deployNow"><Play :size="15"/>Executar Deploy</button></section>
  <section class="panel table-panel"><header><div><strong>Histórico e Pipelines</strong><span>Estado anterior, versão implantada, healthcheck e rollback.</span></div><Boxes :size="19"/></header><div class="table-wrap"><table><thead><tr><th>Ambiente</th><th>Repositório</th><th>Ref</th><th>Status</th><th>Health</th><th>Data</th><th></th></tr></thead><tbody><tr v-for="record in deployments" :key="record.id"><td>{{targetMap[record.target_id]||record.target_id}}</td><td>{{record.repository_id?repositoryMap[record.repository_id]:'—'}}</td><td><code>{{record.requested_ref||'—'}}</code></td><td><span class="status" :class="statusClass(record.status)">{{record.status}}</span></td><td>{{record.health_result?.ok===true?'OK':record.health_result?.ok===false?'Falhou':'—'}}</td><td>{{when(record.created_at)}}</td><td><button class="button ghost" :disabled="record.status==='running'" @click="rollback(record)"><RotateCcw :size="14"/>Rollback</button></td></tr><tr v-if="!deployments.length"><td colspan="7" class="empty">Nenhum deployment registrado.</td></tr></tbody></table></div></section>
</div></template>

<style scoped>
.notice{display:flex;gap:.7rem;padding:.8rem;border:1px solid color-mix(in srgb,var(--primary) 25%,var(--border));border-radius:.85rem;background:color-mix(in srgb,var(--primary) 5%,var(--surface))}.notice div{display:grid}.notice span,.panel header span,.card header span,.card small{color:var(--text-muted);font-size:.67rem}.panel,.card{border:1px solid var(--border);border-radius:.9rem;background:var(--surface);box-shadow:var(--shadow-sm)}.panel{padding:1rem}.panel>header,.card>header{display:flex;align-items:center;justify-content:space-between;gap:.7rem;margin-bottom:.8rem}.panel header div,.card header div{display:grid}.grid{display:grid;gap:.75rem}.cols-2{grid-template-columns:repeat(2,minmax(0,1fr))}.cols-3{grid-template-columns:repeat(3,minmax(0,1fr))}.code{min-height:7rem;font-family:ui-monospace,SFMono-Regular,Consolas,monospace}.cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(285px,1fr));gap:.8rem}.card{padding:.85rem}.card p{line-height:1.5;color:var(--text)}.actions{display:flex;gap:.5rem;flex-wrap:wrap;margin-top:.8rem}.dot{width:.55rem;height:.55rem;border-radius:50%;background:var(--success);box-shadow:0 0 8px var(--success)}.dot.off{background:var(--text-muted);box-shadow:none}.table-wrap{overflow:auto}table{width:100%;border-collapse:collapse;font-size:.7rem}th,td{padding:.65rem;border-bottom:1px solid var(--border-soft);text-align:left;white-space:nowrap}th{color:var(--text-muted)}.status{padding:.18rem .42rem;border-radius:999px;font-size:.57rem;font-weight:800}.status.ok{color:var(--success);background:color-mix(in srgb,var(--success) 10%,transparent)}.status.warn{color:var(--warning);background:color-mix(in srgb,var(--warning) 10%,transparent)}.status.bad{color:var(--danger);background:color-mix(in srgb,var(--danger) 10%,transparent)}.status.run{color:var(--primary-strong);background:color-mix(in srgb,var(--primary) 10%,transparent)}.empty{text-align:center;color:var(--text-muted)}@media(max-width:820px){.cols-2,.cols-3{grid-template-columns:1fr}.cards{grid-template-columns:1fr}}
</style>
